### ISSUE TITLE
from PIL import image

### ISSUE THREAD

**Issue by joshuaseale13** [jkenlooper/piecemaker#17]
I am facing this issue.
Import "PIL" could not be resolved from source Pylance

Additionally when i run the command:
 piecemaker --dir test  --number-of-pieces 100 test.jpg 

I get

piecemaker : The term 'piecemaker' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+  piecemaker --dir test  --number-of-pieces 100 test.jpg
+  ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (piecemaker:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by jkenlooper** [comment]
This looks like maybe an issue with whatever program is using piecemaker.  Probably failed to install it fully would be my guess.  I'm sorry, but I can't help troubleshoot this issue more than that.
