### ISSUE TITLE
Can you share sample outputs?

### ISSUE THREAD

**Issue by mqudsi** [jkenlooper/piecemaker#29]
Hello, 

Would it be possible to add sample outputs to the README file so that we can see what shape the puzzle pieces come out as? There are a lot of different possible shapes, some puzzle software emits very regular/repetitive shapes that can be fit together incorrectly other has more unique piece shapes for better results. It would be helpful to see what this looks like!

**Comment by jkenlooper** [comment]
Yeah, this could be done by creating a few sample puzzles and then just grabbing some of the generated pieces to add to the README. I suppose that would help when someone is quickly evaluting this and doesn't have the time or desire to run the 'piecemaker.sh' script.

**Comment by mqudsi** [comment]
I’ll upload my sample layouts here.

**Comment by jkenlooper** [comment]
I've also include a few rendered pieces. I want to keep the repo size small, so didn't include the full rendered output.

**Comment by mqudsi** [comment]
Thanks. I understand about keeping the repo size small for sure; what I actually meant was along the lines of the attached SVG, though, to be able to see all the various shapes and whether or not the shapes are repeating, etc.

![lines](https://github.com/jkenlooper/piecemaker/assets/606923/1b5e17e7-2875-458f-a2be-7e76c7791316)

**Comment by jkenlooper** [comment]
Yeah, that would be better to show the svg for a sample like that. I just added that one to the README. Thanks.
