### ISSUE TITLE
got an unexpected keyword argument 'mask_dir'

### ISSUE THREAD

**Issue by topalabogdan** [jkenlooper/piecemaker#3]
```
  File "c:\users\me\desktop\puzzle\process.py\piecemaker-master\src\piecemaker\base.py", line 86, in __init__
    self._pixsaw_handler = PMHandler(mydir, linesfile, mask_dir='mask',raster_dir='raster')
TypeError: __init__() got an unexpected keyword argument 'mask_dir'
```

why i get this errror ?

**Comment by jkenlooper** [comment]
You will need the latest pixsaw which has mask_dir.  I don't think I ever released a newer version for pixsaw, so you'll need to download it from the master branch and link to it.  https://github.com/jkenlooper/pixsaw

**Comment by jkenlooper** [comment]
I've released the newest versions for both pixsaw and piecemaker.
